---
services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:2.14.3
    container_name: stirling-pdf
    restart: unless-stopped
    volumes:
      - "stirling_pdf_data:/configs"
    environment:
      - SECURITY_ENABLELOGIN=false
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stirling-pdf.rule=Host(`stirling.eastie.boston`)"
      - "traefik.http.routers.stirling-pdf.entrypoints=websecure"
      - "traefik.http.routers.stirling-pdf.tls.certresolver=cloudflare"
      - "traefik.http.services.stirling-pdf.loadbalancer.server.port=8080"

networks:
  traefik:
    external: true

volumes:
  stirling_pdf_data:
