nuc:
  hosts:
    big-slice:
      ansible_host: 10.20.0.15
raspberry_pi:
  hosts:
    small-slice-01:
      ansible_host: 10.20.0.11
    small-slice-02:
      ansible_host: 10.20.0.12
    small-slice-03:
      ansible_host: 10.20.0.13
    small-slice-04:
      ansible_host: 10.20.0.14
docker_hosts:
  children:
    nuc:
    raspberry_pi:
