---
collections:
  - name: community.docker
    version: ">=4.7.0"
  - name: community.general
    version: ">=11.2.1"
  - name: ansible.posix
    version: ">=2.1.0"

roles:
  - name: geerlingguy.docker
    version: "7.5.3"
