---
collections:
  - name: community.docker
    version: ">=4.8.1"
  - name: community.general
    version: ">=11.4.1"
  - name: ansible.posix
    version: ">=2.1.0"

roles:
  - name: geerlingguy.docker
    version: "7.8.0"
  - name: geerlingguy.nut_client
    version: "2.0.0"
