---
collections:
  - name: community.docker
    version: ">=5.0.5"
  - name: community.general
    version: ">=12.2.0"
  - name: ansible.posix
    version: ">=2.1.0"

roles:
  - name: geerlingguy.docker
    version: "7.9.0"
  - name: geerlingguy.nut_client
    version: "2.0.0"
