services:
  scrypted:
    image: ghcr.io/koush/scrypted:v0.144.1-noble-full
    container_name: scrypted
    restart: unless-stopped
    network_mode: host
    volumes:
      - /etc/avahi/services:/etc/avahi/services:ro
      - scrypted-data:/server/volume
    devices:
      - "/dev/dri:/dev/dri"
    environment:
      - SCRYPTED_DOCKER_AVAHI=true
    logging:
      driver: "none"

volumes:
  scrypted-data:
