---
services:
  dkron:
    image: dkron/dkron:4.2.0
    container_name: dkron
    restart: unless-stopped
    ports:
      - "8081:8080"
      - "8946:8946/tcp"
      - "8946:8946/udp"
      - "6868:6868"
    volumes:
      - ./dkron.yml:/etc/dkron/dkron.yml:ro
      - dkron_data:/dkron.data
    command: agent

volumes:
  dkron_data:
