---
# Main infrastructure server
hardware:
  model: Minisforum MS-01
  type: nuc

docker_services:
  - backup-core
  - code-server
  - convertx
  - drawio
  - excalidraw
  - graylog
  - handbrake
  - homepage
  - it-tools
  - kiwix
  - monitoring
  - network-optimizer
  - nut-server
  - portainer
  - rackula
  - stirling-pdf
  - traefik

# NUT configuration override for local server
nut_client_server: 127.0.0.1

# Docker configuration override for local syslog server
docker_daemon_syslog_address: 127.0.0.1
