---
# Main infrastructure server
hardware:
  model: Minisforum MS-01
  type: nuc

# Static ULA IPv6 address (LAN VLAN)
network_ula_ipv6_address: fdf8:151d:2d13::21/64

docker_services:
  - backup-core
  - code-server
  - convertx
  - drawio
  - excalidraw
  - handbrake
  - homepage
  - it-tools
  - kiwix
  - monitoring
  - network-optimizer
  - nut-server
  - ollama
  - portainer
  - rackula
  - stirling-pdf
  - traefik

# NUT configuration override for local server
nut_client_server: 127.0.0.1

# Docker configuration override for local syslog server
docker_daemon_syslog_address: 127.0.0.1
