---
# Pi cluster server 4
hardware:
  model: Raspberry Pi 4
  type: raspberry_pi

# Static ULA IPv6 address (Common VLAN)
network_ula_ipv6_address: fdf8:151d:2d13:30::14/64

docker_services:
  - backup-scrypted
  - dockerproxy
  - monitoring-agent
  - portainer-agent
  - scrypted
