---
title: Eastie Home Lab
theme: dark
color: neutral
favicon: https://benprisby.com/favicon.ico

useEqualHeights: true
disableCollapse: true

layout:
  Monitoring:
    style: row
    columns: 4
  Network:
    style: row
    columns: 4
  Infrastructure:
    style: row
    columns: 3
  Media:
    style: row
    columns: 3
  Development:
    style: row
    columns: 4
  AI:
    style: row
    columns: 4
  Design:
    style: row
    columns: 3
  Documents:
    style: row
    columns: 2
  Smart Home:
    style: row
    columns: 3
