---
services:
  convertx:
    image: ghcr.io/c4illin/convertx:v0.18.0
    container_name: convertx
    restart: unless-stopped
    volumes:
      - "convertx_data:/app/data"
    environment:
      - HTTP_ALLOWED=true
      - ALLOW_UNAUTHENTICATED=true
      - UNAUTHENTICATED_USER_SHARING=true
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.convertx.rule=Host(`convertx.eastie.boston`)"
      - "traefik.http.routers.convertx.entrypoints=websecure"
      - "traefik.http.routers.convertx.tls.certresolver=cloudflare"
      - "traefik.http.services.convertx.loadbalancer.server.port=3000"

networks:
  traefik:
    external: true

volumes:
  convertx_data:
