---
services:
  code-server:
    image: lscr.io/linuxserver/code-server:4.131.0
    container_name: code-server
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
      - PASSWORD=${CODE_SERVER_PASSWORD}
      - DEFAULT_WORKSPACE=/workspace/docker
    volumes:
      - "code_server_data:/config"
      - "/home/lbp/docker:/workspace/docker"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.code-server.rule=Host(`code.eastie.boston`)"
      - "traefik.http.routers.code-server.entrypoints=websecure"
      - "traefik.http.routers.code-server.tls.certresolver=cloudflare"
      - "traefik.http.services.code-server.loadbalancer.server.port=8443"

networks:
  traefik:
    external: true

volumes:
  code_server_data:
